import React, { useEffect, useState } from "react";
import Head from "next/head";
import NavBar from "../components/NavBarOthers";
import StationCard from "../components/StationCard";
import useLang from "../Providers/LangContext";
// stations
import enStationsData from "../data/en/stations.json";
import esStationsData from "../data/es/stations.json";

const stations = () => {
  const [lang] = useLang();
  const [data, setStations] = useState(esStationsData);
  useEffect(() => {
    if (lang === "ES") {
      setStations(esStationsData);
    } else if (lang === "EN") {
      setStations(enStationsData);
    }
  }, [lang]);
  return (
    <>
      <Head>
        <title>Transmi App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <NavBar />
      <main className="stationsContainer">
        {data.stations.map((station, id) => (
          <StationCard key={id} data={station} />
        ))}
      </main>
    </>
  );
};

export default stations;
